FROM python:3.7-slim

WORKDIR /usr/src/app
COPY cloudfunctions/statsfunction ./
COPY docker/stats.sh ./
COPY docker/db_connection_docker.py ./db_connection.py

RUN pip install functions-framework gunicorn
RUN pip install -r requirements.txt


CMD ["sh", "stats.sh"]