FROM python:3.7-slim

WORKDIR /usr/src/app
COPY cloudfunctions/queuefunction ./
COPY docker/queue.sh ./
COPY docker/db_connection_docker.py ./db_connection.py

RUN apt-get update && apt-get install git -y && git clone https://github.com/googleapis/python-pubsub.git
RUN pip install -r python-pubsub/samples/snippets/requirements.txt
RUN pip install functions-framework gunicorn
RUN pip install -r requirements.txt


CMD ["sh", "queue.sh"]